# Generated by Django 2.2.7 on 2021-01-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('modificada', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificada')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudEstados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50, verbose_name='Rol de aplicación')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicia en')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado en')),
                ('recolector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Usuario', verbose_name='Recolector')),
            ],
        ),
        migrations.CreateModel(
            name='ViajeSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Solicitud')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Viaje')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDomicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(blank=True, max_length=250, null=True)),
                ('geox', models.CharField(blank=True, max_length=50, null=True)),
                ('geoy', models.CharField(blank=True, max_length=50, null=True)),
                ('default', models.BooleanField(default=False)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Provincia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.UsuarioRol'),
        ),
        migrations.CreateModel(
            name='SolicitudMensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(blank=True, max_length=250, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Material')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.SolicitudEstados'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Usuario'),
        ),
    ]
