# Generated by Django 2.2.7 on 2021-01-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolicitudEstados',
            new_name='SolicitudEstado',
        ),
    ]
