# Generated by Django 2.2.7 on 2021-01-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20210106_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincia',
            name='habilitada',
            field=models.BooleanField(default=False),
        ),
    ]
