# Generated by Django 2.2.7 on 2021-01-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_provincia_habilitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorol',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
