# Generated by Django 2.2.7 on 2021-01-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20210106_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Nueva'), (2, 'Asignada'), (3, 'Planificada'), (4, 'En curso'), (5, 'Cerrada'), (6, 'Cancelada')]),
        ),
        migrations.DeleteModel(
            name='SolicitudEstado',
        ),
    ]
