# Generated by Django 2.2.7 on 2021-01-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20210108_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='domicilio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.UsuarioDomicilio'),
        ),
    ]
