# Generated by Django 2.2.7 on 2021-01-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_solicitud_materiales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudMaterial',
        ),
    ]
