# Generated by Django 2.2.7 on 2021-01-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_delete_solicitudmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='codigo',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
