# Generated by Django 2.2.7 on 2021-01-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_material_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='codigo',
            field=models.CharField(max_length=2),
        ),
    ]
