# Generated by Django 2.2.7 on 2021-01-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20210109_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='materiales',
            field=models.CharField(max_length=250),
        ),
    ]
