# Generated by Django 2.2.7 on 2021-01-09 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0012_auto_20210109_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoRecoleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.CharField(blank=True, max_length=250, null=True)),
                ('geox', models.CharField(blank=True, max_length=50, null=True)),
                ('geoy', models.CharField(blank=True, max_length=50, null=True)),
                ('es_global', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.Material')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.PuntoRecoleccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='domicilio',
        ),
        migrations.DeleteModel(
            name='UsuarioDomicilio',
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis.Solicitud'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='punto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.UsuarioPunto'),
        ),
    ]
