# Generated by Django 2.2.7 on 2021-01-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_auto_20210109_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(),
        ),
    ]
