# Generated by Django 2.2.7 on 2021-01-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_auto_20210109_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='eliminado',
            new_name='eliminada',
        ),
    ]
