# Generated by Django 2.2.7 on 2021-01-09 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0016_auto_20210109_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='asignada',
            field=models.DateTimeField(null=True, verbose_name='Asignada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='recolector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recolector', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
