# Generated by Django 2.2.7 on 2021-01-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_auto_20210109_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='asignada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Asignada'),
        ),
    ]
