# Generated by Django 2.2.7 on 2021-01-09 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_auto_20210109_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='cancelada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cerrada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cerrada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='en_curso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='En curso'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='planificada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Planificada'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='recolector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recolector', to=settings.AUTH_USER_MODEL),
        ),
    ]
