# Generated by Django 2.2.7 on 2021-01-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_auto_20210109_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_planificada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recolección planificada'),
        ),
    ]
