# Generated by Django 2.2.7 on 2021-01-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_solicitud_fecha_planificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='viaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apis.Viaje'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='pos_x',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='coordenadas x'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='pos_y',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='coordenadas x'),
        ),
    ]
