# Generated by Django 2.2.7 on 2021-01-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_auto_20210110_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViajeSolicitud',
        ),
    ]
