# Generated by Django 2.2.7 on 2021-01-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_delete_viajesolicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
