# Generated by Django 2.2.7 on 2021-01-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_auto_20210110_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntorecoleccion',
            name='comentario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='puntorecoleccion',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='puntorecoleccion',
            name='horario',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
